[development]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "normal"
#secret_key = "aaaaaaaaaaaaaaaaaaaaa"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "normal"
#secret_key = "[randomly generated at launch]"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 5
log = "critical"
#secret_key = "[randomly generated at launch]"
limits = { forms = 32768 }
