name: Rust

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ]
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build_backend:
    env:
      HOME: "/home/axiom"
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./backend
      run: cargo build --verbose --release

    - name: Pack
      - run: zip ./application.zip ./backend/target/release/Project-5B-Telemedicine-Application*
    - name: Upload
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./application.zip
