name: Build Frontend
on: 
  push:
    branches:
      - frontend
    tags: # Always, regardless of paths above
        - '*'
jobs:
  build_frontend:

    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Building Site
        working-directory: ./frontend
        run: npm run build --if-present
