name: Rust

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ main ]
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build_backend:
    env:
      HOME: "/home/axiom"
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./backend
      run: cargo build --verbose