name: Build Frontend
on: [push]
  branches:
    - frontend
      tags: # Always, regardless of paths above
      - '*'
jobs:
  build_frontend:
    runs-on: pi
    name: Build frontend
    steps:
    - uses: actions/checkout@v2
      working-directory: ./frontend
    - id: Build-Frontend
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'Axioms'
        reponame: 'Project-5B-Telemedicine-Application'
        token: ${{ secrets.GITHUB_TOKEN }}